# Write a program to input 8 numbers from the user and display all the unique numbers (once).
s = set()
n = int(input("Enter the number: "))
s.add(int(n))
n = int(input("Enter the number: "))
s.add(int(n))
n = int(input("Enter the number: "))
s.add(int(n))
n = int(input("Enter the number: "))
s.add(int(n))
n = int(input("Enter the number: "))
s.add(int(n))
n = int(input("Enter the number: "))
s.add(int(n))
n = int(input("Enter the number: "))
s.add(int(n))
n = int(input("Enter the number: "))
s.add(int(n))

print(s)